# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 534)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background: #131415;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: #fff;\n"
"    background: hsla(0, 0%, 100%, 0.1);\n"
"    width: 170px;\n"
"    height: 25px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: hsla(0, 0%, 100%, 0.2);\n"
"}\n"
"\n"
"#main_area{\n"
"    background: #131415;\n"
"    display: none;\n"
"}\n"
"\n"
"#test_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#test_subtitle{\n"
"    color: #aaa;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#test_console_title{\n"
"    color: #fff;\n"
"    background: hsl(240, 5%, 5%);\n"
"    padding: 5px 10px;\n"
"    border-bottom: 2px solid #000;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    font-size: 16px;\n"
"    font-family: \'Consolas\';\n"
"}\n"
"\n"
"#test_console_result{\n"
"    color: #fff;\n"
"    color: hsl(0, 100%, 75%);\n"
"    selection-background-color: #fff;\n"
"    selection-color: #000;\n"
"    background: hsl(240, 5%, 5%);\n"
"    padding: 5px 0px 5px 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    font-size: 16px;\n"
"    font-family: \'Consolas\';\n"
"}\n"
"\n"
"#tests_list,\n"
"#sub_tests_list,\n"
"#sub_test_list__layout,\n"
"#tests_list__scroll_area,\n"
"#tests_list__scroll_area__layout{\n"
"    background: hsl(220, 5%, 12%);\n"
"    border: none;\n"
"}\n"
"\n"
"#tests_list,\n"
"#sub_tests_list{\n"
"    border-right: 2px solid #111;\n"
"}\n"
"\n"
"#tests_list__scroll_area QScrollBar{\n"
"    width: 0px;\n"
"}\n"
"\n"
"#run_test_btn,\n"
"#run_the_test_btn{\n"
"    background: hsl(240, 100%, 56%);\n"
"}\n"
"#run_test_btn:hover,\n"
"#run_the_test_btn:hover{\n"
"    background: hsl(240, 100%, 63%);\n"
"}\n"
"\n"
"#test_re_selected_btn,\n"
"#test_ok_btn,\n"
"#test_pe_btn,\n"
"#test_tl_btn,\n"
"#test_ml_btn,\n"
"#test_wa_btn,\n"
"#test_re_btn{\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#test_ok_btn{\n"
"    background: hsl(130, 60%, 25%);\n"
"}\n"
"#test_ok_btn:hover{\n"
"    background: hsl(130, 60%, 30%);\n"
"}\n"
"\n"
"#test_pe_btn,\n"
"#test_tl_btn,\n"
"#test_ml_btn{\n"
"    background: hsl(67, 60%, 25%);\n"
"}\n"
"#test_pe_btn:hover,\n"
"#test_tl_btn:hover,\n"
"#test_ml_btn:hover{\n"
"    background: hsl(67, 60%, 30%);\n"
"}\n"
"\n"
"#test_wa_btn{\n"
"    background: hsl(0, 60%, 25%);\n"
"}\n"
"#test_wa_btn:hover{\n"
"    background: hsl(0, 60%, 30%);\n"
"}\n"
"\n"
"#test_re_btn{\n"
"    background: hsl(300, 60%, 25%);\n"
"}\n"
"#test_re_btn:hover{\n"
"    background: hsl(300, 60%, 30%);\n"
"}\n"
"\n"
"#test_re_selected_btn{\n"
"    background: hsl(300, 60%, 30%);\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 5px;\n"
"}")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_edit_area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_edit_area.sizePolicy().hasHeightForWidth())
        self.main_edit_area.setSizePolicy(sizePolicy)
        self.main_edit_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_edit_area.setStyleSheet("QMainWindow{\n"
"    background: #131415;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: #fff;\n"
"    background: hsla(0, 0%, 100%, 0.1);\n"
"    width: 170px;\n"
"    height: 25px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: hsla(0, 0%, 100%, 0.2);\n"
"}\n"
"\n"
"#main_area{\n"
"    background: #131415;\n"
"}\n"
"\n"
"#edit_test_btn,\n"
"#export_test_btn,\n"
"#import_test_btn{\n"
"    background: hsla(0, 0%, 100%, 0.1);\n"
"}\n"
"#edit_test_btn:hover,\n"
"#export_test_btn:hover,\n"
"#import_test_btn:hover{\n"
"    background: hsla(0, 0%, 100%, 0.2);\n"
"}\n"
"\n"
"#test_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#test_subtitle{\n"
"    color: #aaa;\n"
"    /* margin-bottom: 35px; */\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#test_console_title{\n"
"    color: #fff;\n"
"    background: hsl(240, 5%, 5%);\n"
"    padding: 5px 10px;\n"
"    border-bottom: 2px solid #000;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    font-size: 16px;\n"
"    font-family: \'Consolas\';\n"
"}\n"
"\n"
"#test_console_result{\n"
"    color: #fff;\n"
"    color: hsl(0, 100%, 75%);\n"
"    selection-background-color: #fff;\n"
"    selection-color: #000;\n"
"    background: hsl(240, 5%, 5%);\n"
"    padding: 5px 0px 5px 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    font-size: 16px;\n"
"    font-family: \'Consolas\';\n"
"}\n"
"\n"
"#test_verdict,\n"
"#test_error,\n"
"#test_time_limit,\n"
"#test_memory_limit,\n"
"#test_time,\n"
"#test_memory,\n"
"#test_input_type,\n"
"#test_output_type{\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#tests_list{\n"
"    background: hsl(220, 5%, 12%);\n"
"}\n"
"\n"
"#start_test_btn{\n"
"    background: hsl(240, 100%, 56%);\n"
"}\n"
"#start_test_btn:hover{\n"
"    background: hsl(240, 100%, 63%);\n"
"}\n"
"\n"
"#add_test_btn{\n"
"    background: hsla(0, 0%, 100%, 0.1);\n"
"}\n"
"#add_test_btn:hover{\n"
"    background: hsla(0, 0%, 100%, 0.2);\n"
"}\n"
"\n"
"#test_re_selected_btn,\n"
"#test_ok_btn,\n"
"#test_pe_btn,\n"
"#test_tl_btn,\n"
"#test_ml_btn,\n"
"#test_wa_btn,\n"
"#test_re_btn{\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#test_ok_btn{\n"
"    background: hsl(130, 60%, 25%);\n"
"}\n"
"#test_ok_btn:hover{\n"
"    background: hsl(130, 60%, 30%);\n"
"}\n"
"\n"
"#test_pe_btn,\n"
"#test_tl_btn,\n"
"#test_ml_btn{\n"
"    background: hsl(67, 60%, 25%);\n"
"}\n"
"#test_pe_btn:hover,\n"
"#test_tl_btn:hover,\n"
"#test_ml_btn:hover{\n"
"    background: hsl(67, 60%, 30%);\n"
"}\n"
"\n"
"#test_wa_btn{\n"
"    background: hsl(0, 60%, 25%);\n"
"}\n"
"#test_wa_btn:hover{\n"
"    background: hsl(0, 60%, 30%);\n"
"}\n"
"\n"
"#test_re_btn{\n"
"    background: hsl(300, 60%, 25%);\n"
"}\n"
"#test_re_btn:hover{\n"
"    background: hsl(300, 60%, 30%);\n"
"}\n"
"\n"
"#test_re_selected_btn{\n"
"    background: hsl(300, 60%, 30%);\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 5px;\n"
"}")
        self.main_edit_area.setObjectName("main_edit_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_edit_area)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.edit_test_top_area = QtWidgets.QHBoxLayout()
        self.edit_test_top_area.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.edit_test_top_area.setSpacing(10)
        self.edit_test_top_area.setObjectName("edit_test_top_area")
        self.edit_test_info_area = QtWidgets.QWidget(self.main_edit_area)
        self.edit_test_info_area.setMinimumSize(QtCore.QSize(100, 0))
        self.edit_test_info_area.setMaximumSize(QtCore.QSize(16777215, 85))
        self.edit_test_info_area.setObjectName("edit_test_info_area")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.edit_test_info_area)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.test_title_edit = QtWidgets.QLineEdit(self.edit_test_info_area)
        self.test_title_edit.setObjectName("test_title_edit")
        self.verticalLayout_12.addWidget(self.test_title_edit)
        self.test_subtitle_edit = QtWidgets.QPlainTextEdit(self.edit_test_info_area)
        self.test_subtitle_edit.setMinimumSize(QtCore.QSize(0, 48))
        self.test_subtitle_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.test_subtitle_edit.setObjectName("test_subtitle_edit")
        self.verticalLayout_12.addWidget(self.test_subtitle_edit)
        self.edit_test_top_area.addWidget(self.edit_test_info_area)
        self.edit_test_btn_area = QtWidgets.QWidget(self.main_edit_area)
        self.edit_test_btn_area.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_test_btn_area.setMaximumSize(QtCore.QSize(16777215, 85))
        self.edit_test_btn_area.setObjectName("edit_test_btn_area")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.edit_test_btn_area)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.save_test_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.save_test_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.save_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_test_btn.setObjectName("save_test_btn")
        self.verticalLayout_11.addWidget(self.save_test_btn)
        self.cancel_edit_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.cancel_edit_btn.setEnabled(True)
        self.cancel_edit_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.cancel_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_edit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancel_edit_btn.setObjectName("cancel_edit_btn")
        self.verticalLayout_11.addWidget(self.cancel_edit_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem)
        self.edit_test_top_area.addWidget(self.edit_test_btn_area)
        self.verticalLayout_2.addLayout(self.edit_test_top_area)
        self.details_area_edit = QtWidgets.QFormLayout()
        self.details_area_edit.setHorizontalSpacing(5)
        self.details_area_edit.setVerticalSpacing(10)
        self.details_area_edit.setObjectName("details_area_edit")
        self.edit_checker_label = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_checker_label.sizePolicy().hasHeightForWidth())
        self.edit_checker_label.setSizePolicy(sizePolicy)
        self.edit_checker_label.setMinimumSize(QtCore.QSize(135, 0))
        self.edit_checker_label.setMaximumSize(QtCore.QSize(135, 17))
        self.edit_checker_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edit_checker_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_checker_label.setObjectName("edit_checker_label")
        self.details_area_edit.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.edit_checker_label)
        self.edit_checker_combo = QtWidgets.QComboBox(self.main_edit_area)
        self.edit_checker_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_checker_combo.setObjectName("edit_checker_combo")
        self.edit_checker_combo.addItem("")
        self.edit_checker_combo.addItem("")
        self.edit_checker_combo.addItem("")
        self.edit_checker_combo.addItem("")
        self.edit_checker_combo.addItem("")
        self.edit_checker_combo.addItem("")
        self.details_area_edit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_checker_combo)
        self.label = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(135, 0))
        self.label.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label.setObjectName("label")
        self.details_area_edit.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_checker_arg_1 = QtWidgets.QPlainTextEdit(self.main_edit_area)
        self.edit_checker_arg_1.setObjectName("edit_checker_arg_1")
        self.details_area_edit.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_checker_arg_1)
        self.label_2 = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(135, 0))
        self.label_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName("label_2")
        self.details_area_edit.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edit_checker_arg_2 = QtWidgets.QPlainTextEdit(self.main_edit_area)
        self.edit_checker_arg_2.setObjectName("edit_checker_arg_2")
        self.details_area_edit.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_checker_arg_2)
        self.label_3 = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(135, 0))
        self.label_3.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.details_area_edit.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_file_path = QtWidgets.QLineEdit(self.main_edit_area)
        self.edit_file_path.setMinimumSize(QtCore.QSize(0, 25))
        self.edit_file_path.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.edit_file_path.setObjectName("edit_file_path")
        self.horizontalLayout_2.addWidget(self.edit_file_path)
        self.open_file_path_btn = QtWidgets.QPushButton(self.main_edit_area)
        self.open_file_path_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_file_path_btn.setObjectName("open_file_path_btn")
        self.horizontalLayout_2.addWidget(self.open_file_path_btn)
        self.details_area_edit.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.details_area_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.main_edit_area)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autotest"))
        self.test_title_edit.setText(_translate("MainWindow", "Проверка деления на 0"))
        self.test_subtitle_edit.setPlainText(_translate("MainWindow", "Если модуль вернёт None, то тест будет считаться пройденным, если заверишться c ошибкой, то нет"))
        self.save_test_btn.setText(_translate("MainWindow", "Сохранить"))
        self.cancel_edit_btn.setText(_translate("MainWindow", "Отмена"))
        self.edit_checker_label.setText(_translate("MainWindow", "Чекер:"))
        self.edit_checker_combo.setItemText(0, _translate("MainWindow", "console_to_console"))
        self.edit_checker_combo.setItemText(1, _translate("MainWindow", "console_to_file"))
        self.edit_checker_combo.setItemText(2, _translate("MainWindow", "console_to_error"))
        self.edit_checker_combo.setItemText(3, _translate("MainWindow", "file_to_file"))
        self.edit_checker_combo.setItemText(4, _translate("MainWindow", "file_to_console"))
        self.edit_checker_combo.setItemText(5, _translate("MainWindow", "file_to_error"))
        self.label.setText(_translate("MainWindow", "Входные данные:"))
        self.label_2.setText(_translate("MainWindow", "Выходные данные:"))
        self.label_3.setText(_translate("MainWindow", "Тестируемый файл:"))
        self.edit_file_path.setText(_translate("MainWindow", "C:/Users/cergmin/AtApplication/project/main.py"))
        self.open_file_path_btn.setText(_translate("MainWindow", "Выбрать файл"))
