from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 534)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        
        with open('./styles.qss', 'r', encoding='utf-8') as styles:
                MainWindow.setStyleSheet(styles.read())

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.tests_list = QtWidgets.QWidget(self.centralwidget)
        self.tests_list.setMinimumSize(QtCore.QSize(170, 0))
        self.tests_list.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tests_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tests_list.setAutoFillBackground(False)
        self.tests_list.setObjectName("tests_list")
        self.horizontalLayout.addWidget(self.tests_list)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.tests_list)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")

        self.run_test_btn = QtWidgets.QPushButton(self.tests_list)
        self.run_test_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.run_test_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.run_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_test_btn.setObjectName("run_test_btn")

        self.verticalLayout.addWidget(self.run_test_btn)
        self.add_test_btn = QtWidgets.QPushButton(self.tests_list)
        self.add_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_test_btn.setObjectName("add_test_btn")
        self.verticalLayout.addWidget(self.add_test_btn)

        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)

        self.tests_list__scroll_area = QtWidgets.QScrollArea(self.tests_list)
        self.tests_list__scroll_area.setWidgetResizable(True)
        self.tests_list__scroll_area.setObjectName("tests_list__scroll_area")
        self.tests_list__widget = QtWidgets.QWidget()
        self.tests_list__widget.setGeometry(QtCore.QRect(0, 0, 150, 205))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tests_list__widget.sizePolicy().hasHeightForWidth())
        self.tests_list__widget.setSizePolicy(sizePolicy)
        self.tests_list__widget.setMinimumSize(QtCore.QSize(150, 0))
        self.tests_list__widget.setObjectName("tests_list__widget")

        self.tests_list__layout = QtWidgets.QVBoxLayout(self.tests_list__widget)
        self.tests_list__layout.setContentsMargins(0, 0, 0, 0)
        self.tests_list__layout.setSpacing(5)
        self.tests_list__layout.setObjectName("tests_list__layout")

        self.tests_list__scroll_area.setWidget(self.tests_list__widget)
        self.verticalLayout.addWidget(self.tests_list__scroll_area)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        
        self.verticalLayout.addItem(spacerItem1)
        self.settings_btn = QtWidgets.QPushButton(self.tests_list)
        self.settings_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout.addWidget(self.settings_btn)

        self.sub_tests_list = QtWidgets.QScrollArea(self.centralwidget)
        self.sub_tests_list.setMinimumSize(QtCore.QSize(170, 0))
        self.sub_tests_list.setMaximumSize(QtCore.QSize(170, 16777215))
        self.sub_tests_list.setWidgetResizable(True)
        self.sub_tests_list.setObjectName("sub_tests_list")
        self.sub_test_list__widget = QtWidgets.QWidget()
        self.sub_test_list__widget.setGeometry(QtCore.QRect(0, 0, 168, 225))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_test_list__widget.sizePolicy().hasHeightForWidth())
        
        self.sub_test_list__widget.setSizePolicy(sizePolicy)
        self.sub_test_list__widget.setMinimumSize(QtCore.QSize(150, 0))
        self.sub_test_list__widget.setObjectName("sub_test_list__widget")

        self.sub_test_list__layout = QtWidgets.QVBoxLayout(self.sub_test_list__widget)
        self.sub_test_list__layout.setContentsMargins(8, 10, 10, 10)
        self.sub_test_list__layout.setSpacing(5)
        self.sub_test_list__layout.setObjectName("sub_test_list__layout")

        self.sub_tests_list.setWidget(self.sub_test_list__widget)
        self.horizontalLayout.addWidget(self.sub_tests_list)
        self.main_area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_area.sizePolicy().hasHeightForWidth())
        self.main_area.setSizePolicy(sizePolicy)
        self.main_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_area.setObjectName("main_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_area)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.test_top_area = QtWidgets.QHBoxLayout()
        self.test_top_area.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.test_top_area.setSpacing(10)
        self.test_top_area.setObjectName("test_top_area")
        self.test_info_area = QtWidgets.QWidget(self.main_area)
        self.test_info_area.setMinimumSize(QtCore.QSize(100, 0))
        self.test_info_area.setObjectName("test_info_area")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.test_info_area)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.test_title = QtWidgets.QLabel(self.test_info_area)
        self.test_title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_title.sizePolicy().hasHeightForWidth())
        self.test_title.setSizePolicy(sizePolicy)
        self.test_title.setMinimumSize(QtCore.QSize(0, 0))
        self.test_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.test_title.setWordWrap(True)
        self.test_title.setObjectName("test_title")
        self.verticalLayout_12.addWidget(self.test_title)
        self.test_subtitle = QtWidgets.QLabel(self.test_info_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_subtitle.sizePolicy().hasHeightForWidth())
        self.test_subtitle.setSizePolicy(sizePolicy)
        self.test_subtitle.setMinimumSize(QtCore.QSize(0, 48))
        self.test_subtitle.setMaximumSize(QtCore.QSize(400, 80))
        self.test_subtitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.test_subtitle.setWordWrap(True)
        self.test_subtitle.setObjectName("test_subtitle")
        self.verticalLayout_12.addWidget(self.test_subtitle)
        self.test_top_area.addWidget(self.test_info_area)
        self.edit_test_btn_area = QtWidgets.QWidget(self.main_area)
        self.edit_test_btn_area.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_test_btn_area.setObjectName("edit_test_btn_area")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.edit_test_btn_area)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.run_the_test_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.run_the_test_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.run_the_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_the_test_btn.setObjectName("run_the_test_btn")
        self.verticalLayout_11.addWidget(self.run_the_test_btn)
        self.edit_test_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.edit_test_btn.setEnabled(True)
        self.edit_test_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.edit_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_test_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edit_test_btn.setObjectName("edit_test_btn")
        self.verticalLayout_11.addWidget(self.edit_test_btn)
        self.pushButton = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.pushButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        self.test_top_area.addWidget(self.edit_test_btn_area)
        self.verticalLayout_2.addLayout(self.test_top_area)
        self.details_area = QtWidgets.QHBoxLayout()
        self.details_area.setObjectName("details_area")
        self.test_details = QtWidgets.QWidget(self.main_area)
        self.test_details.setMinimumSize(QtCore.QSize(230, 0))
        self.test_details.setObjectName("test_details")

        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.test_details)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")

        self.test_verdict = QtWidgets.QLabel(self.test_details)
        self.test_verdict.setMinimumSize(QtCore.QSize(230, 22))
        self.test_verdict.setMaximumSize(QtCore.QSize(250, 22))
        self.test_verdict.setTextFormat(QtCore.Qt.RichText)
        self.test_verdict.setObjectName("test_verdict")
        self.verticalLayout_13.addWidget(self.test_verdict)

        # self.test_error = QtWidgets.QLabel(self.test_details)
        # self.test_error.setMinimumSize(QtCore.QSize(230, 22))
        # self.test_error.setMaximumSize(QtCore.QSize(250, 22))
        # self.test_error.setTextFormat(QtCore.Qt.RichText)
        # self.test_error.setObjectName("test_error")
        # self.verticalLayout_13.addWidget(self.test_error)

        # self.test_time_limit = QtWidgets.QLabel(self.test_details)
        # self.test_time_limit.setMinimumSize(QtCore.QSize(230, 22))
        # self.test_time_limit.setMaximumSize(QtCore.QSize(250, 22))
        # self.test_time_limit.setTextFormat(QtCore.Qt.RichText)
        # self.test_time_limit.setObjectName("test_time_limit")
        # self.verticalLayout_13.addWidget(self.test_time_limit)

        # self.test_memory_limit = QtWidgets.QLabel(self.test_details)
        # self.test_memory_limit.setMinimumSize(QtCore.QSize(230, 22))
        # self.test_memory_limit.setMaximumSize(QtCore.QSize(250, 22))
        # self.test_memory_limit.setTextFormat(QtCore.Qt.RichText)
        # self.test_memory_limit.setObjectName("test_memory_limit")
        # self.verticalLayout_13.addWidget(self.test_memory_limit)

        # self.test_time = QtWidgets.QLabel(self.test_details)
        # self.test_time.setMinimumSize(QtCore.QSize(230, 22))
        # self.test_time.setMaximumSize(QtCore.QSize(250, 22))
        # self.test_time.setTextFormat(QtCore.Qt.RichText)
        # self.test_time.setObjectName("test_time")
        # self.verticalLayout_13.addWidget(self.test_time)

        # self.test_memory = QtWidgets.QLabel(self.test_details)
        # self.test_memory.setMinimumSize(QtCore.QSize(230, 22))
        # self.test_memory.setMaximumSize(QtCore.QSize(250, 22))
        # self.test_memory.setTextFormat(QtCore.Qt.RichText)
        # self.test_memory.setObjectName("test_memory")
        # self.verticalLayout_13.addWidget(self.test_memory)

        self.test_checker = QtWidgets.QLabel(self.test_details)
        self.test_checker.setMinimumSize(QtCore.QSize(230, 22))
        self.test_checker.setMaximumSize(QtCore.QSize(250, 22))
        self.test_checker.setTextFormat(QtCore.Qt.RichText)
        self.test_checker.setObjectName("test_checker")
        self.verticalLayout_13.addWidget(self.test_checker)

        self.test_checker_arg_1 = QtWidgets.QLabel(self.test_details)
        self.test_checker_arg_1.setMinimumSize(QtCore.QSize(230, 22))
        self.test_checker_arg_1.setMaximumSize(QtCore.QSize(250, 22))
        self.test_checker_arg_1.setTextFormat(QtCore.Qt.RichText)
        self.test_checker_arg_1.setObjectName("test_checker_arg_1")
        self.verticalLayout_13.addWidget(self.test_checker_arg_1)

        self.test_checker_arg_2 = QtWidgets.QLabel(self.test_details)
        self.test_checker_arg_2.setMinimumSize(QtCore.QSize(230, 22))
        self.test_checker_arg_2.setMaximumSize(QtCore.QSize(250, 22))
        self.test_checker_arg_2.setTextFormat(QtCore.Qt.RichText)
        self.test_checker_arg_2.setObjectName("test_checker_arg_2")
        self.verticalLayout_13.addWidget(self.test_checker_arg_2)

        self.test_file_path = QtWidgets.QLabel(self.test_details)
        self.test_file_path.setMinimumSize(QtCore.QSize(230, 22))
        self.test_file_path.setMaximumSize(QtCore.QSize(250, 22))
        self.test_file_path.setTextFormat(QtCore.Qt.RichText)
        self.test_file_path.setObjectName("test_file_path")
        self.verticalLayout_13.addWidget(self.test_file_path)
        
        self.details_area.addWidget(self.test_details)
        self.test_console = QtWidgets.QVBoxLayout()
        self.test_console.setSpacing(0)
        self.test_console.setObjectName("test_console")
        self.test_console_title = QtWidgets.QLabel(self.main_area)
        self.test_console_title.setMinimumSize(QtCore.QSize(0, 35))
        self.test_console_title.setMaximumSize(QtCore.QSize(16777215, 35))
        self.test_console_title.setObjectName("test_console_title")
        self.test_console.addWidget(self.test_console_title)
        self.test_console_result = QtWidgets.QPlainTextEdit(self.main_area)
        self.test_console_result.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_console_result.sizePolicy().hasHeightForWidth())
        self.test_console_result.setSizePolicy(sizePolicy)
        self.test_console_result.setMinimumSize(QtCore.QSize(0, 210))
        self.test_console_result.setReadOnly(True)
        self.test_console_result.setObjectName("test_console_result")
        self.test_console.addWidget(self.test_console_result)
        self.details_area.addLayout(self.test_console)
        self.verticalLayout_2.addLayout(self.details_area)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.main_area)

        # Ниже идёт виджет редактирования теста - main_edit_area
        self.main_edit_area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_edit_area.sizePolicy().hasHeightForWidth())
        self.main_edit_area.setSizePolicy(sizePolicy)
        self.main_edit_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_edit_area.setObjectName("main_edit_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_edit_area)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.edit_test_top_area = QtWidgets.QHBoxLayout()
        self.edit_test_top_area.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.edit_test_top_area.setSpacing(10)
        self.edit_test_top_area.setObjectName("edit_test_top_area")
        self.edit_test_info_area = QtWidgets.QWidget(self.main_edit_area)
        self.edit_test_info_area.setMinimumSize(QtCore.QSize(100, 0))
        self.edit_test_info_area.setMaximumSize(QtCore.QSize(16777215, 85))
        self.edit_test_info_area.setObjectName("edit_test_info_area")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.edit_test_info_area)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.test_title_edit = QtWidgets.QLineEdit(self.edit_test_info_area)
        self.test_title_edit.setObjectName("test_title_edit")
        self.verticalLayout_12.addWidget(self.test_title_edit)
        self.test_subtitle_edit = QtWidgets.QPlainTextEdit(self.edit_test_info_area)
        self.test_subtitle_edit.setMinimumSize(QtCore.QSize(0, 48))
        self.test_subtitle_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.test_subtitle_edit.setObjectName("test_subtitle_edit")
        self.verticalLayout_12.addWidget(self.test_subtitle_edit)
        self.edit_test_top_area.addWidget(self.edit_test_info_area)
        self.edit_test_btn_area = QtWidgets.QWidget(self.main_edit_area)
        self.edit_test_btn_area.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_test_btn_area.setMaximumSize(QtCore.QSize(16777215, 85))
        self.edit_test_btn_area.setObjectName("edit_test_btn_area")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.edit_test_btn_area)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.save_test_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.save_test_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.save_test_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_test_btn.setObjectName("save_test_btn")
        self.verticalLayout_11.addWidget(self.save_test_btn)
        self.cancel_edit_btn = QtWidgets.QPushButton(self.edit_test_btn_area)
        self.cancel_edit_btn.setEnabled(True)
        self.cancel_edit_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.cancel_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_edit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancel_edit_btn.setObjectName("cancel_edit_btn")
        self.verticalLayout_11.addWidget(self.cancel_edit_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem)
        self.edit_test_top_area.addWidget(self.edit_test_btn_area)
        self.verticalLayout_2.addLayout(self.edit_test_top_area)
        self.details_area_edit = QtWidgets.QFormLayout()
        self.details_area_edit.setHorizontalSpacing(5)
        self.details_area_edit.setVerticalSpacing(10)
        self.details_area_edit.setObjectName("details_area_edit")
        self.edit_checker_label = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_checker_label.sizePolicy().hasHeightForWidth())
        self.edit_checker_label.setSizePolicy(sizePolicy)
        self.edit_checker_label.setMinimumSize(QtCore.QSize(135, 0))
        self.edit_checker_label.setMaximumSize(QtCore.QSize(135, 17))
        self.edit_checker_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edit_checker_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_checker_label.setObjectName("edit_checker_label")
        self.details_area_edit.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.edit_checker_label)
        self.edit_checker_combo = QtWidgets.QComboBox(self.main_edit_area)
        self.edit_checker_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_checker_combo.setObjectName("edit_checker_combo")
        self.details_area_edit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_checker_combo)
        self.label = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(135, 0))
        self.label.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label.setObjectName("label")
        self.details_area_edit.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_checker_arg_1 = QtWidgets.QPlainTextEdit(self.main_edit_area)
        self.edit_checker_arg_1.setObjectName("edit_checker_arg_1")
        self.details_area_edit.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_checker_arg_1)
        self.label_2 = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(135, 0))
        self.label_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName("label_2")
        self.details_area_edit.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edit_checker_arg_2 = QtWidgets.QPlainTextEdit(self.main_edit_area)
        self.edit_checker_arg_2.setObjectName("edit_checker_arg_2")
        self.details_area_edit.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_checker_arg_2)
        self.label_3 = QtWidgets.QLabel(self.main_edit_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(135, 0))
        self.label_3.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.details_area_edit.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_file_path = QtWidgets.QLineEdit(self.main_edit_area)
        self.edit_file_path.setMinimumSize(QtCore.QSize(0, 25))
        self.edit_file_path.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.edit_file_path.setObjectName("edit_file_path")
        self.horizontalLayout_2.addWidget(self.edit_file_path)
        self.open_file_path_btn = QtWidgets.QPushButton(self.main_edit_area)
        self.open_file_path_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_file_path_btn.setObjectName("open_file_path_btn")
        self.horizontalLayout_2.addWidget(self.open_file_path_btn)
        self.details_area_edit.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.details_area_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.main_edit_area)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AtAplication"))
        self.run_test_btn.setText(_translate("MainWindow", "Тестировать"))
        self.add_test_btn.setText(_translate("MainWindow", "Добавить"))
        self.settings_btn.setText(_translate("MainWindow", "Настройки"))
        self.run_the_test_btn.setText(_translate("MainWindow", "Запустить этот тест"))
        self.edit_test_btn.setText(_translate("MainWindow", "Редактировать тест"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить детали"))
        self.test_title.setText(_translate("MainWindow", "Заголовок теста"))
        self.test_subtitle.setText(_translate("MainWindow", "Подзаголовок теста"))
        self.test_console_title.setText(_translate("MainWindow", "Console"))

        self.test_title_edit.setText(_translate("MainWindow", "Проверка деления на 0"))
        self.test_subtitle_edit.setPlainText(_translate("MainWindow", "Если модуль вернёт None, то тест будет считаться пройденным, если заверишться c ошибкой, то нет"))
        self.save_test_btn.setText(_translate("MainWindow", "Сохранить"))
        self.cancel_edit_btn.setText(_translate("MainWindow", "Отмена"))
        self.edit_checker_label.setText(_translate("MainWindow", "Чекер:"))
        self.edit_checker_combo.setItemText(0, _translate("MainWindow", "console_to_console"))
        self.edit_checker_combo.setItemText(1, _translate("MainWindow", "console_to_file"))
        self.edit_checker_combo.setItemText(2, _translate("MainWindow", "console_to_error"))
        self.edit_checker_combo.setItemText(3, _translate("MainWindow", "file_to_file"))
        self.edit_checker_combo.setItemText(4, _translate("MainWindow", "file_to_console"))
        self.edit_checker_combo.setItemText(5, _translate("MainWindow", "file_to_error"))
        self.label.setText(_translate("MainWindow", "Входные данные:"))
        self.label_2.setText(_translate("MainWindow", "Выходные данные:"))
        self.label_3.setText(_translate("MainWindow", "Тестируемый файл:"))
        self.edit_file_path.setText(_translate("MainWindow", "C:/Users/cergmin/AtApplication/project/main.py"))
        self.open_file_path_btn.setText(_translate("MainWindow", "Выбрать файл"))